import { searchDemandStrains } from "./searchDemandData";

const raw = [
  ["Gruntz","hybrid","20–24%",["Relaxed","Happy","Creative"],["Caryophyllene","Limonene","Linalool"],["Berry","Candy","Earthy"],"Gelato × Zkittlez",["Gelato","Zkittlez","Runtz"],"A fruit-forward hybrid with a candy-sweet aroma, balanced character, and an easygoing finish.","9–10 weeks"],
  ["Blue Dream","hybrid","17–24%",["Uplifted","Creative","Relaxed"],["Myrcene","Pinene","Caryophyllene"],["Blueberry","Herbal","Sweet"],"Blueberry × Haze",["Super Silver Haze","Strawberry Cough","Pineapple Express"],"A berry-led hybrid with a bright herbal finish and an easygoing character.","9–10 weeks"],
  ["Wedding Cake","hybrid","20–27%",["Relaxed","Happy","Calm"],["Caryophyllene","Limonene","Myrcene"],["Vanilla","Pepper","Earthy"],"Triangle Kush × Animal Mints",["Gelato","Ice Cream Cake","Biscotti"],"A rich dessert-style hybrid with vanilla, pepper, and earthy depth.","8–10 weeks"],
  ["Lemon Cherry Gelato","hybrid","20–28%",["Happy","Relaxed","Euphoric"],["Caryophyllene","Limonene","Linalool"],["Lemon","Cherry","Cream"],"Sunset Sherbet × Girl Scout Cookies × Lemon phenotype",["Gelato","Cherry Pie","Wedding Cake"],"A citrus-and-cherry dessert profile with a creamy finish.","8–10 weeks"],
  ["Ice Cream Cake","indica","20–25%",["Relaxed","Calm","Sleepy"],["Caryophyllene","Limonene","Linalool"],["Vanilla","Cream","Earthy"],"Wedding Cake × Gelato #33",["Wedding Cake","Gelato","Biscotti"],"A creamy, vanilla-forward cultivar with a deeply settled character.","8–9 weeks"],
  ["Permanent Marker","hybrid","22–30%",["Euphoric","Relaxed","Creative"],["Caryophyllene","Limonene","Myrcene"],["Floral","Fuel","Candy"],"Biscotti × Jealousy × Sherb Bx",["Jealousy","Biscotti","Gelato"],"A bold floral, candy, and fuel profile with lingering intensity.","8–10 weeks"],
  ["Apple Fritter","hybrid","22–28%",["Relaxed","Happy","Creative"],["Caryophyllene","Limonene","Pinene"],["Apple","Pastry","Earthy"],"Sour Apple × Animal Cookies",["Wedding Cake","Gelato","Apples and Bananas"],"Sweet baked-apple notes meet earth and spice in this balanced hybrid.","8–10 weeks"],
  ["Biscotti","indica","21–25%",["Relaxed","Euphoric","Calm"],["Caryophyllene","Limonene","Myrcene"],["Cookie","Diesel","Nutty"],"Gelato #25 × South Florida OG",["Gelato","Wedding Cake","Permanent Marker"],"Cookie sweetness, diesel, and nutty spice define this dense profile.","8–9 weeks"],
  ["Cereal Milk","hybrid","18–25%",["Happy","Creative","Relaxed"],["Caryophyllene","Limonene","Myrcene"],["Cream","Berry","Vanilla"],"Y Life × Snowman",["Gelato","Runtz","Wedding Cake"],"Creamy cereal-milk sweetness layered with berry and vanilla notes.","8–10 weeks"],
  ["Gelato","hybrid","20–26%",["Relaxed","Euphoric","Happy"],["Caryophyllene","Limonene","Myrcene"],["Cream","Citrus","Berry"],"Sunset Sherbet × Thin Mint GSC",["Wedding Cake","Runtz","Ice Cream Cake"],"A creamy citrus-and-berry profile that helped define modern dessert strains.","8–10 weeks"],
  ["Runtz","hybrid","19–29%",["Happy","Relaxed","Euphoric"],["Caryophyllene","Limonene","Linalool"],["Candy","Tropical","Berry"],"Zkittlez × Gelato",["White Runtz","Pink Runtz","Gelato"],"Candy sweetness and tropical fruit meet a smooth, creamy finish.","8–9 weeks"],
  ["Super Boof","hybrid","20–28%",["Uplifted","Focused","Relaxed"],["Limonene","Caryophyllene","Myrcene"],["Cherry","Citrus","Earthy"],"Black Cherry Punch × Tropicana Cookies",["Cherry Pie","Tropicana Cookies","Gelato"],"Bright cherry and citrus notes sit over an earthy, slightly funky base.","8–10 weeks"],
  ["Northern Lights","indica","16–21%",["Relaxed","Sleepy","Calm"],["Myrcene","Caryophyllene","Pinene"],["Earthy","Pine","Sweet"],"Afghani × Thai landrace heritage",["Purple Punch","OG Kush","White Widow"],"A classic earthy-pine profile known for a quiet, deeply relaxing character.","7–9 weeks"],
  ["Sour Diesel","sativa","18–26%",["Energized","Uplifted","Focused"],["Caryophyllene","Limonene","Myrcene"],["Diesel","Citrus","Herbal"],"Chemdawg and Super Skunk lineage",["Jack Herer","Green Crack","Durban Poison"],"Sharp diesel aroma with citrus lift and a distinctly energetic profile.","9–11 weeks"],
  ["Glitter Bomb","hybrid","20–28%",["Relaxed","Happy","Euphoric"],["Caryophyllene","Limonene","Myrcene"],["Grape","Berry","Fuel"],"Grape Gas × OGKB Blueberry Headband",["Purple Punch","Carbon Fiber","Permanent Marker"],"Dark grape and berry sweetness combine with a polished fuel note.","8–10 weeks"],
  ["Jack Herer","sativa","18–24%",["Focused","Creative","Uplifted"],["Terpinolene","Caryophyllene","Pinene"],["Pine","Spice","Herbal"],"Haze × Northern Lights #5 × Shiva Skunk",["Sour Diesel","Durban Poison","White Widow"],"Pine, spice, and herbs frame a clear, lively sativa character.","9–10 weeks"],
  ["Gary Payton","hybrid","20–25%",["Focused","Relaxed","Euphoric"],["Caryophyllene","Limonene","Pinene"],["Diesel","Pepper","Sweet"],"The Y × Snowman",["Cereal Milk","Jealousy","Permanent Marker"],"Sweet diesel and pepper meet a composed, balanced hybrid profile.","8–9 weeks"],
  ["Pineapple Express","hybrid","18–25%",["Energized","Happy","Creative"],["Caryophyllene","Limonene","Myrcene"],["Pineapple","Pine","Citrus"],"Trainwreck × Hawaiian",["Blue Dream","Strawberry Cough","Green Crack"],"Tropical pineapple and citrus brighten a fresh pine backbone.","8–10 weeks"],
  ["OG Kush","hybrid","19–26%",["Relaxed","Happy","Euphoric"],["Myrcene","Limonene","Caryophyllene"],["Earthy","Pine","Fuel"],"Chemdawg × Lemon Thai × Hindu Kush lineage",["Sour Diesel","Northern Lights","Bubba Kush"],"Earth, pine, citrus, and fuel form one of the best-known modern profiles.","8–9 weeks"],
  ["White Widow","hybrid","18–25%",["Euphoric","Creative","Relaxed"],["Myrcene","Caryophyllene","Pinene"],["Earthy","Woody","Pepper"],"Brazilian sativa × South Indian indica",["Jack Herer","Northern Lights","Blue Dream"],"Woody earth and pepper accompany a classic balanced-hybrid character.","8–10 weeks"],
  ["Strawberry Cough","sativa","17–23%",["Uplifted","Talkative","Focused"],["Myrcene","Pinene","Caryophyllene"],["Strawberry","Sweet","Herbal"],"Strawberry Fields × Haze",["Blue Dream","Pineapple Express","Jack Herer"],"Fresh strawberry sweetness and soft herbs define this social sativa profile.","9–10 weeks"],
  ["White Truffle","indica","18–26%",["Relaxed","Calm","Euphoric"],["Caryophyllene","Limonene","Myrcene"],["Earthy","Mushroom","Fuel"],"Gorilla Butter phenotype",["GG4","Gorilla Butter","Biscotti"],"Savory earth, mushroom, and fuel notes create a distinctive deep profile.","8–10 weeks"],
  ["Zoap","hybrid","20–26%",["Happy","Creative","Relaxed"],["Caryophyllene","Limonene","Linalool"],["Floral","Soap","Citrus"],"Rainbow Sherbet × Pink Guava",["Jealousy","Gelato","Permanent Marker"],"Floral, clean-soap, and citrus notes make this profile unusually recognizable.","8–10 weeks"],
  ["Green Crack","sativa","17–24%",["Energized","Focused","Uplifted"],["Myrcene","Caryophyllene","Pinene"],["Mango","Citrus","Earthy"],"Skunk #1 lineage",["Sour Diesel","Durban Poison","Jack Herer"],"Mango and citrus sit over an earthy base in this brisk sativa profile.","7–9 weeks"],
  ["Pink Runtz","hybrid","20–28%",["Happy","Euphoric","Relaxed"],["Caryophyllene","Limonene","Linalool"],["Candy","Berry","Cream"],"Runtz phenotype/selection",["Runtz","White Runtz","Gelato"],"Pink candy, berry, and cream notes create a playful dessert profile.","8–9 weeks"],
  ["White Runtz","hybrid","20–29%",["Relaxed","Happy","Euphoric"],["Caryophyllene","Limonene","Linalool"],["Candy","Citrus","Earthy"],"Zkittlez × Gelato selection",["Runtz","Pink Runtz","Gelato"],"Candy and citrus brightness settle into a creamy, earthy finish.","8–9 weeks"],
  ["Oreoz","indica","20–30%",["Relaxed","Euphoric","Calm"],["Caryophyllene","Limonene","Myrcene"],["Chocolate","Cookie","Diesel"],"Cookies and Cream × Secret Weapon",["Biscotti","Ice Cream Cake","Wedding Cake"],"Chocolate-cookie sweetness and diesel depth shape this dense dessert profile.","8–10 weeks"],
  ["Purple Punch","indica","18–25%",["Relaxed","Sleepy","Happy"],["Caryophyllene","Myrcene","Limonene"],["Grape","Berry","Vanilla"],"Larry OG × Granddaddy Purple",["Northern Lights","Glitter Bomb","Ice Cream Cake"],"Grape, berry, and vanilla notes accompany a softly settling character.","8–9 weeks"],
  ["Cap Junky","hybrid","23–31%",["Euphoric","Creative","Relaxed"],["Caryophyllene","Limonene","Myrcene"],["Fruit","Pepper","Fuel"],"Alien Cookies × Kush Mints #11",["Kush Mints","Permanent Marker","Gary Payton"],"Fruit, black pepper, and fuel create a potent, complex modern profile.","8–10 weeks"],
  ["Durban Poison","sativa","17–25%",["Energized","Focused","Creative"],["Terpinolene","Myrcene","Ocimene"],["Sweet","Anise","Pine"],"South African landrace",["Jack Herer","Green Crack","Sour Diesel"],"Sweet anise and pine define this classic, clear sativa expression.","9–11 weeks"],
  ["Jealousy","hybrid","20–30%",["Euphoric","Relaxed","Creative"],["Caryophyllene","Limonene","Myrcene"],["Cream","Pepper","Citrus"],"Sherbert Bx1 × Gelato 41",["Gelato","Permanent Marker","Gary Payton"],"Cream, pepper, and citrus give this modern hybrid a layered finish.","8–10 weeks"],
  ["Apples and Bananas","hybrid","20–28%",["Happy","Creative","Relaxed"],["Caryophyllene","Limonene","Myrcene"],["Apple","Banana","Spice"],"Platinum Cookies × Granddaddy Purple × Blue Power × Gelatti",["Apple Fritter","Cereal Milk","Gelato"],"Ripe apple and banana sweetness meet warm spice and earth.","8–10 weeks"],
  ["Cherry Pie","hybrid","16–24%",["Happy","Relaxed","Creative"],["Myrcene","Caryophyllene","Pinene"],["Cherry","Berry","Earthy"],"Granddaddy Purple × Durban Poison",["Super Boof","Wedding Cake","Blue Dream"],"Tart cherry and berry notes sit over a gently earthy base.","8–9 weeks"],
  ["London Pound Cake","indica","20–29%",["Relaxed","Calm","Happy"],["Caryophyllene","Limonene","Myrcene"],["Berry","Citrus","Vanilla"],"Sunset Sherbet lineage",["Gelato","Wedding Cake","Ice Cream Cake"],"Berry, citrus, and vanilla form a rich bakery-style profile.","8–10 weeks"],
  ["Kush Mints","hybrid","22–28%",["Relaxed","Euphoric","Focused"],["Caryophyllene","Limonene","Myrcene"],["Mint","Coffee","Earthy"],"Animal Mints × Bubba Kush",["Gush Mints","Cap Junky","Biscotti"],"Cool mint, coffee, and earth make this hybrid sharp and distinctive.","8–10 weeks"],
  ["Gush Mints","indica","20–27%",["Relaxed","Calm","Euphoric"],["Caryophyllene","Limonene","Myrcene"],["Mint","Sweet","Earthy"],"Kush Mints × F1 Durb × Gushers",["Kush Mints","Gelato","Biscotti"],"Sweet mint and earth meet a fruit-candy undertone.","8–10 weeks"],
  ["Gumbo","indica","18–25%",["Relaxed","Sleepy","Happy"],["Caryophyllene","Limonene","Myrcene"],["Bubblegum","Sweet","Earthy"],"Reported Bubblegum-family lineage",["Runtz","Pink Runtz","Purple Punch"],"Bubblegum sweetness and soft earth characterize this mellow profile.","8–10 weeks"],
  ["GG4","hybrid","20–28%",["Relaxed","Euphoric","Happy"],["Caryophyllene","Myrcene","Limonene"],["Diesel","Earthy","Chocolate"],"Chem’s Sister × Sour Dubb × Chocolate Diesel",["White Truffle","Sour Diesel","OG Kush"],"Diesel, earth, and dark chocolate make this classic profile unmistakably bold.","8–10 weeks"],
  ["Carbon Fiber","hybrid","20–28%",["Relaxed","Euphoric","Creative"],["Caryophyllene","Limonene","Myrcene"],["Grape","Fuel","Pepper"],"Grape Pie × Biscotti × Cookies and Cream",["Glitter Bomb","Biscotti","Permanent Marker"],"Dark grape, fuel, and pepper combine in a polished modern hybrid.","8–10 weeks"]
];

export const slugify=(name)=>name.toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const curatedStrains=raw.map(([name,type,thc,effects,terpenes,flavor,lineage,similar,summary,flowering])=>({name:`${name} Strain`,shortName:name,type,classification:type,slug:slugify(name),thc,effects,terpenes,flavor,lineage,similar,summary,flowering,price:"$14.99",image:"/products/gruntz.jpg",verifiedProfile:true}));

const flavorThemes=[["Citrus","Sweet","Herbal"],["Berry","Cream","Earthy"],["Fruit","Spice","Pine"],["Floral","Sweet","Woody"],["Dessert","Vanilla","Earthy"],["Tropical","Citrus","Herbal"],["Fuel","Pepper","Earthy"],["Candy","Fruit","Cream"]];
const effectsThemes=[["Batch-specific","COA guided","Adult use"],["Profile varies","Producer documented","Batch specific"],["Cultivar dependent","Lab documented","Adult use"],["Phenotype dependent","COA guided","Profile varies"]];
const hashName=(name)=>[...name].reduce((total,char)=>total+char.charCodeAt(0),0);
const generatedStrains=searchDemandStrains.map((item,index)=>{
  const flavor=flavorThemes[hashName(item.shortName)%flavorThemes.length];
  const effects=effectsThemes[hashName(item.shortName)%effectsThemes.length];
  const previous=searchDemandStrains[(index+searchDemandStrains.length-1)%searchDemandStrains.length].shortName;
  const next=searchDemandStrains[(index+1)%searchDemandStrains.length].shortName;
  return {name:`${item.shortName} Strain`,shortName:item.shortName,type:"hybrid",classification:"Varies by breeder",slug:slugify(item.shortName),thc:"Batch dependent",effects,terpenes:["Batch-specific COA"],flavor,lineage:"Confirm with breeder or producer",similar:[previous,next,"Search-demand comparison"],summary:`A demand-led ${item.shortName} template for organizing batch-specific product, aroma, effect, lineage, and availability information.`,flowering:"Breeder dependent",price:"Check availability",image:"/products/gruntz.jpg",verifiedProfile:false,searchDemand:item.volume,searchIntent:item.intent,keywordDifficulty:item.keywordDifficulty,cpc:item.cpc,sourceRow:item.sourceRow};
});

export const strains=[...curatedStrains,...generatedStrains];
export const getStrain=(type,slug)=>strains.find((s)=>s.type===type&&s.slug===slug);
